apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node_hello
  template:
    metadata:
      labels:
        app: node_hello
    spec:
      containers:
      - name: cntr-hello
        image: hello:0.0.1
        ports:
          - containerPort: 8080