apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: cntr-redis
        image: redis:alpine
        ports:
          - containerPort: 6379
            name: http
---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 6379
      port: 6379
      name: http
  selector:
    app: redis
